#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/../../../.."

: "${NANODISCOVER_LOG_ROOT:=./logs}"
export NANODISCOVER_LOG_ROOT
export NANODISCOVER_RESUME_DIR="${NANODISCOVER_RESUME_DIR:-}"

source tasks/circle_packing/launchers/common_circle_packing_env.sh

# Fast smoke overrides aligned with the public Qwen release path.
export NANODISCOVER_NUM_EPOCHS=1
export NANODISCOVER_SEEDS_PER_EPOCH=1
export NANODISCOVER_ROLLOUTS_PER_SEED=2
export NANODISCOVER_MAX_ARCHIVE_SIZE=16
export NANODISCOVER_GENERATOR_BACKEND=ray_data_llm
export NANODISCOVER_GENERATOR_DATA_PARALLEL_SIZE=2
export NANODISCOVER_GENERATOR_BATCH_SIZE=2
export NANODISCOVER_EVALUATOR_NUM_WORKERS=2
export NANODISCOVER_TRAINER_NUM_WORKERS=2
export NANODISCOVER_TRAINER_MAX_TOKENS_PER_RANK=16384
export NANODISCOVER_SEQUENCE_PARALLEL_SIZE=2
export NANODISCOVER_USE_REMOVE_PADDING=1

export NANODISCOVER_STAGE_START=sample
export NANODISCOVER_STAGE_STOP="${NANODISCOVER_STAGE_STOP:-train}"
export NANODISCOVER_STAGE_MAX_EPOCHS=0

python main.py
