#!/usr/bin/env bash
# shellcheck shell=bash

export NANODISCOVER_TASK_NAME=circle_packing
export NANODISCOVER_CIRCLE_PACKING_N="${NANODISCOVER_CIRCLE_PACKING_N:-26}"
export NANODISCOVER_NUM_EPOCHS=50
export NANODISCOVER_SEEDS_PER_EPOCH=8
export NANODISCOVER_ROLLOUTS_PER_SEED=64
export NANODISCOVER_MAX_ARCHIVE_SIZE=1000
export NANODISCOVER_TOPK_CHILDREN=2
export NANODISCOVER_PUCT_C=1.0

export NANODISCOVER_GENERATOR_DATA_PARALLEL_SIZE=4
export NANODISCOVER_GENERATOR_TENSOR_PARALLEL_SIZE=1
export NANODISCOVER_GENERATOR_BACKEND=ray_data_llm
export NANODISCOVER_MODEL_NAME_OR_PATH="Qwen/Qwen3-8B"
export NANODISCOVER_TOKENIZER_NAME_OR_PATH="Qwen/Qwen3-8B"
export NANODISCOVER_RENDERER_NAME=qwen_chat
export NANODISCOVER_RENDERER_SYSTEM_PROMPT= # Intentionally left empty due to parity with original TTT-Discover code.
export NANODISCOVER_RENDERER_STOP_SEQUENCE="<|im_end|>"
export NANODISCOVER_TEMPERATURE=1.0
export NANODISCOVER_PHASE1_MAX_TOKENS=32718 # Intentionally set to this value to disable phase 2 because original TTT-Discover didn't do it for Qwen3-8B.
export NANODISCOVER_CONTEXT_WINDOW=32768
export NANODISCOVER_CONTEXT_BUFFER=50
export NANODISCOVER_FINAL_ANSWER_MARKER=
export NANODISCOVER_FORCED_FINAL_SUFFIX=
export NANODISCOVER_PHASE1_END_MARKER=
export NANODISCOVER_FORCED_FINAL_SUFFIX_AFTER_PHASE1_END_MARKER=

export NANODISCOVER_GENERATOR_BATCH_SIZE=16
export RAY_NUM_CPUS=48 # Prevent ray from spawning ncpus workers
export NANODISCOVER_EVALUATOR_NUM_WORKERS=48

export NANODISCOVER_TRAIN_BACKEND=deepspeed
export NANODISCOVER_LEARNING_RATE=4e-5
export NANODISCOVER_ADAM_BETA1=0.9
export NANODISCOVER_ADAM_BETA2=0.95
export NANODISCOVER_ADAM_EPS=1e-8
export NANODISCOVER_WEIGHT_DECAY=0.0
export NANODISCOVER_KL_PENALTY_COEF=0.1
export NANODISCOVER_REMOVE_CONSTANT_REWARD_GROUPS=1
export NANODISCOVER_LORA_RANK=32
export NANODISCOVER_LORA_ALPHA=32 # TTT-Discover codebase does not specify it. Tinker's default is 32. https://github.com/thinking-machines-lab/tinker-cookbook/issues/280
export NANODISCOVER_LORA_DROPOUT=0.0
export NANODISCOVER_LORA_TARGET_MODULES="q_proj,k_proj,v_proj,o_proj,gate_proj,up_proj,down_proj,lm_head" # TTT-Discover codebase does not specify it. Tinker's default is to target all linear modules (train_attn=True, train_mlp=True, train_unembed=True) and TTT-Discover does not touch these values.
export NANODISCOVER_NUM_SUBSTEPS=1
export NANODISCOVER_TRAINER_NUM_WORKERS=4
export NANODISCOVER_TRAINER_MAX_TOKENS_PER_RANK=16384
export NANODISCOVER_REFERENCE_SCORING_MAX_TOKENS_PER_RANK=16384
export NANODISCOVER_TRAINER_LOGPROB_COMPUTE_DTYPE=float32
export NANODISCOVER_REFERENCE_LOGPROB_VOCAB_CHUNK_SIZE=4096
export NANODISCOVER_REFERENCE_SCORING_MODEL_PARALLEL_SIZE=1
export NANODISCOVER_SEQUENCE_PARALLEL_SIZE=4
export NANODISCOVER_USE_REMOVE_PADDING=1
export NANODISCOVER_GRADIENT_CHECKPOINTING=1
export NANODISCOVER_OPTIMIZER_STATE_KEEP_WINDOW=2

# These are fixed DeepSpeed invariants today, not public tuning knobs.
export NANODISCOVER_DISTRIBUTED_STRATEGY=ddp

# Reduce allocator fragmentation risk for long-sequence training workloads.
export PYTORCH_CUDA_ALLOC_CONF="${PYTORCH_CUDA_ALLOC_CONF:-expandable_segments:True}"

export NANODISCOVER_STAGE_START=sample
export NANODISCOVER_STAGE_STOP=train
export NANODISCOVER_STAGE_MAX_EPOCHS=0

# Runtime compatibility and warning-noise controls.
export RAY_USE_UVLOOP=0
export RAY_ACCEL_ENV_VAR_OVERRIDE_ON_ZERO=0
export PYDANTIC_DISABLE_PLUGINS=1
if [[ -n "${TRANSFORMERS_CACHE:-}" && -z "${HF_HOME:-}" ]]; then
  export HF_HOME="$TRANSFORMERS_CACHE"
fi
unset TRANSFORMERS_CACHE
unset NCCL_P2P_DISABLE
